### ISSUE TITLE
Getting errors while running fasster

### ISSUE THREAD

**Issue by samistat08** [mitchelloharawild/fasster#20]
First of, the package is really great, thanks a lot ! I have already used `msts` to define the time series (passenger_count) but I get the following warning of not using time series, 

`
fasster:::fasster(numberOfPassengersTimeseries, passenger_count ~ temperature + Rain,  heuristic = c("filterSmooth")) %>% ggfitted
`

> Warning message:
> In fasster:::fasster(numberOfPassengersTimeseries, passenger_count ~  :
>   Time series information not found, please provide a tsibble or time-series object.
> 

I also add the coefficients of AR and MA as vectors but I get error. Can you please give an example of a arma added to fasster? 

Thanks in advance

**Comment by mitchelloharawild** [comment]
Hi,

If you could provide a minimally reproducible example (MRE) or the issue with data included, then I'd be able to look into it. ts type objects will soon be deprecated, so I suggest trying to transform the model into a tsibble using `tsibble::as_tsibble()` (from the [earowang/tsibble](https://github.com/earowang/tsibble/) package).

An example of including ARMA terms in the model is as below:
```r
fasster(USAccDeaths ~ poly(1) + trig(12) + ARMA(c(0.9,0.4), c(0.4))) %>% ggfitted
```
A vector of coefficients for the AR and MA coefficients is provided in the first and second argument. I'm planning to work on implementing automatic coefficient selection sometime soon (before cran release).

**Comment by samistat08** [comment]
Thank you for your response, I just added `as_tsibble()` to the dataframe and also ARMA terms that I got from 'auto.arima' on my time series in advance, but I still get the warning of not finding time series and also error on not being able to apply 'arima'. I had a look at your code to understand the error but I would be thankful if you explain it a bit more. Maybe I do not need to add 'arima' at all and 'poly' and 'trig' do the job! 
Here is my data,
```
# A tibble: 4,174 x 5
   dates               passenger_count humidity temperature dayType
 * <fct>                         <int>    <dbl>       <dbl> <chr>  
 1 2017-01-01 01:00:00           41123    100         -2.00 weekend
 2 2017-01-01 02:00:00           37704    100         -1.00 weekend
 3 2017-01-01 03:00:00           31199    100         -2.00 weekend
 4 2017-01-01 04:00:00           22346     98.0       -2.00 weekend
 5 2017-01-01 05:00:00           11123    100         -1.00 weekend
 6 2017-01-01 06:00:00            7946    100         -2.00 weekend
 7 2017-01-01 07:00:00            6710     99.0       -2.00 weekend
 8 2017-01-01 08:00:00            6704     94.0       -2.00 weekend
 9 2017-01-01 09:00:00            9251     94.0       -2.00 weekend
10 2017-01-01 10:00:00           14598     95.0       -1.00 weekend
```
and here is my code , 

`
fitCovariateWeeklyEffect <- fasster(
   as.tibble(trainDataFrame),
   passenger_count ~ dayType +
   humidity +
   temperature +
   poly(2) +
   trig(24 * 7) + 
   ARMA(c(1.5678, -0.7679), c(0.0442, -0.1660, 0.1209, 0.3053, 0.0947)))
`
and the error, 

> Error in dlmSmooth.dlmFiltered(filtered) : 
>   error code 1 from Lapack routine dgesdd
> In addition: Warning message:
> In fasster(as.tibble(trainDataFrame), passenger_count ~ dayType +  :
>   Time series information not found, please provide a tsibble or time-series object.
> 
>

**Comment by mitchelloharawild** [comment]
Hi, the issue is still relating to the way you are providing your dataset to the function.

Your model specification looks reasonable (although you may want to switch via the dayType rather than regress on it) and should work. I'm not sure what you're referring to with the `arima` error, any details on this would be appreciated.

The dataset provided in the first argument is being coerced to a `tibble` (not `tsibble`), and in this dataset it appears that the `dates` column is a factor, not a date time (it should appear as dttm in the print output).

I'm still not entirely sure what the `trainDataFrame` looks like, so I don't know for sure... but this may work:

```r
library(fasster)
library(tsibble)
fitCovariateWeeklyEffect <- fasster(as_tsibble(trainDataFrame), passenger_count ~ dayType + humidity + temperature + poly(2) + trig(24 * 7) + ARMA(c(1.5678, -0.7679), c(0.0442, -0.1660, 0.1209, 0.3053, 0.0947)))
```

To implement switching over `dayType` rather than regressing on it, you can use:
```r
library(fasster)
library(tsibble)
fitCovariateWeeklyEffect <- fasster(as_tsibble(trainDataFrame), passenger_count ~ dayType %S% (humidity + temperature + poly(2) + trig(24 * 7) + ARMA(c(1.5678, -0.7679), c(0.0442, -0.1660, 0.1209, 0.3053, 0.0947))))
```

**Comment by samistat08** [comment]
That was a valid problem, I have fixed it and now data look like this, 

```
# A tsibble: 4,174 x 5 [1HOUR]
   dates               passenger_count humidity temperature dayType
   <dttm>                        <int>    <dbl>       <dbl> <chr>  
 1 2017-01-01 01:00:00           41123    100         -2.00 weekend
 2 2017-01-01 02:00:00           37704    100         -1.00 weekend
 3 2017-01-01 03:00:00           31199    100         -2.00 weekend
 4 2017-01-01 04:00:00           22346     98.0       -2.00 weekend
 5 2017-01-01 05:00:00           11123    100         -1.00 weekend
 6 2017-01-01 06:00:00            7946    100         -2.00 weekend
 7 2017-01-01 07:00:00            6710     99.0       -2.00 weekend
 8 2017-01-01 08:00:00            6704     94.0       -2.00 weekend
 9 2017-01-01 09:00:00            9251     94.0       -2.00 weekend
10 2017-01-01 10:00:00           14598     95.0       -1.00 weekend
# ... with 4,164 more rows
```
By running `fasster` with or even without `temperature` and `humidity` ( I have tried all different combinations! ) ,
```
fitCovariateWeeklyEffect <- 
   fasster(as_tsibble(trainDataFrame),
   passenger_count ~ dayType %S%
   (humidity +
   temperature +
   poly(2) +
   trig(24 * 7) +
   ARMA(c(1.5678, -0.7679), 
   c(0.0442, -0.1660, 0.1209, 0.3053, 0.0947))))

```
 and I still get the following error all the time;

> Error in dlmSmooth.dlmFiltered(filtered) : 
>  error code 1 from Lapack routine dgesdd

**Comment by mitchelloharawild** [comment]
Looks like you are using the package correctly now. This error suggests that the dlm smoothing function from the dlm package failed to converge, which is a result of model specification and data inputs.

I plan to implement alternative implementations for filtering and smoothing the series, however at this stage the only solution to this is to simplify the model or change the parameters.

**Comment by samistat08** [comment]
That is what I got from this error before so have tried the other simpler models and it worked in some cases (e.g. removing `arma` and covariates or removing switching variable and `arma`). But even when `the fitted vs actual values` graph looks promising, the prediction of the model is really wrong (negative values !) checking the `decompose` graph, I can see that the model can capture the trend and specially the unusual event in the data quiet well but it is not able to predict. If you are interested I can send you my analysis result to dig in more. 
Furthermore, it works really slow and takes a long time for computations. Is there a way to boost it for faster performance?

**Comment by mitchelloharawild** [comment]
The inclusion of a poly(2) term may be absorbing all of the error and making your fitted values look better than the model actually performs. Have a look at the decomposition plot (via autoplot) to see if any of your model components is collecting too much noise.

If you need to enforce non-negativity, you can do so using a BoxCox transformation. Feel free to send me some analysis and I'll look for things to improve, the heuristics being applied still require improvement to control for over-flexible poly() terms.

**Comment by samistat08** [comment]
Is it possible to send you by email?

**Comment by mitchelloharawild** [comment]
Sure, my email is in the maintainer field.

**Comment by JustGitting** [comment]
Hi @samistat08, 

I don't mean to hijack this thread, but do you mind sharing how you used auto.arima to manually create the AR and MR weights?

I've tried to extract the coefficients as follows, but I get the following error.

```
arima_fit <- auto.arima(x_train)
ma <- arima_fit$coef[1] 
ar <- arima_fit$coef[2] 

fit <- x_train %>% 
 fasster( count ~ (poly(1) + trig(7) + ARMA(ar, ma) ))
```

> Error in GG[1:p, 1] <- ar : 
>   number of items to replace is not a multiple of replacement length
> In addition: Warning message:
> In (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  :
>   row names were found from a short variable and have been discarded

Cheers

**Comment by mitchelloharawild** [comment]
Looks like a bug to me (probably something to do with scoping). Try manually entering the `ar` and `ma` values and see if that works.

I'm currently working on a tidy version of the forecast package, which will provide a lot of helper functions to improve parsing the formula and evaluating objects in the correct location. Once these helper functions are complete, there will be a near re-write of this package to fix these problems (and hopefully make it faster and easier to use).

**Comment by JustGitting** [comment]
Hi,

Thanks for your quick reply, looks like you are correct.

I tried it manually as follows:

```
fit <- x_train %>% 
 fasster( count ~ (poly(1) + trig(7) + ARMA(c(0.3457), c(-0.8176813)) ))
```

However, looks like it did not converge:

> Error in dlmSmooth.dlmFiltered(filtered) : 
>   error code 1 from Lapack routine dgesdd

**Comment by mitchelloharawild** [comment]
That's unfortunate :disappointed: 

For now, try adjusting the model specification or sample of data. There's a couple of things planned to improve convergence and speed. In particular, I would like to implement different heuristic estimation techniques, and start using sparse matrices (which I expect to drastically improve performance issues).

**Comment by JustGitting** [comment]
Another questions. I'm guess ARMA(ar,ma) cannot accept the coefficients that result from using external regressors if used in arima_fit(x, xreg=xreg), is that right?

**Comment by mitchelloharawild** [comment]
Well, ARMA(ar,ma) can accept any coefficeints, the problem is if the coefficients are appropriate or not.
At this stage I haven't yet looked into how you may be able to estimate appropriate coefficients (I hope that improvements to the heuristic estimation procedure will fix this).

xreg or not, the coefficient estimates that you are obtaining are probably not appropriate because they don't consider the other terms included in the FASSTER model.
