### ISSUE TITLE
Edit suggestion for slide 42 (http://www.mitchelloharawild.com/melburn17)

### ISSUE THREAD

**Issue by leungi** [mitchelloharawild/fasster#30]
I was trying to reproduce your example and notice one small edit that may help future users :)

```
library(lubridate)
library(forecast)

tbl_taylor <- as_tsibble(taylor) %>%
  mutate(index = seq(ymd_h("2000-6-5 00"), by="30 mins", length.out=length(taylor)),
         DayType = ifelse(wday(index) %in% 2:6, "Weekday", "Weekend")) %>% 
  filter(month(index) == 8)

tbl_taylor %>%
  filter(index < ymd("2000-8-21")) %>%

  # original line
  # fasster(taylor~ DayType %S% (poly(1) + trig(48, 16))) %>%

  # revised line
  fasster(value ~ DayType %S% (poly(1) + trig(48, 16))) %>%
 
  forecast(newdata=tbl_taylor %>%
             filter(index >= ymd("2000-8-21"))) %>%
  autoplot() + 
  ylab("Electricity Demand (Megawatts)") + 
  xlab("Time (5 June 2000 - 27 August 2000)")
```

**Comment by mitchelloharawild** [comment]
Yes, the slides for the melburn17 presentation are now out of date.
The package was changed substantially in the lead up to the useR!2018 conference, to support the [fable package](https://github.com/tidyverts/fable).

I'll add a note saying that the presentation is out of date. If you haven't already seen them, the latest slides about this package (which should currently work) can be found here: https://www.mitchelloharawild.com/user2018/#1

**Comment by mitchelloharawild** [comment]
I've updated the slides to include a warning.

**Comment by leungi** [comment]
Cool; I should've picked up from the slide's name it's 1 year old :)

Thanks for the updated slides.
