### ISSUE TITLE
parse_model no longer returns args 

### ISSUE THREAD

**Issue by kayleahaynes** [mitchelloharawild/fasster#32]
Hello, I appreciate this is a very new bug which has come with a recent update in the `fablelite` package but I thought I would flag.  I'm really enjoying exploring the capabilities of this package so hopefully this can be resolved soon.  

model.R has a bug where 

```
dlmModel <- model_inputs$args %>%
    unlist(recursive = FALSE) %>%
    reduce(`+`)
``` 

should be 

```
dlmModel <- model_inputs$specials %>%
    unlist(recursive = FALSE) %>%
    reduce(`+`)
``` 

this is also the case for other places where parse_model is used.  I can't seem to push my fixed code which is why this is an issue and not a pull request.

**Comment by mitchelloharawild** [comment]
Thanks! Fixed in e9e20924d2c1b71a9773dbf15d48004e2d541458.
