### ISSUE TITLE
Does Fasster handle transformations during fit?

### ISSUE THREAD

**Issue by tyokota** [mitchelloharawild/fasster#35]
Does Fasster perform similarly to the `forecast` package in that it can handle transformations in model and then back transform at forecasting, such as taking the difference or a seasonal decomposition?

**Comment by mitchelloharawild** [comment]
fasster accepts most transformations and is able to back-transform them automatically.
For more details on the transformation capabilities, you can read the vignette from the fable package.
```r
vignette("transformations", package="fable")
```

Seasonal decomposition (such as using STL to forecast as described in https://otexts.org/fpp2/forecasting-decomposition.html) is possible, but not yet implemented. Decomposition forecasting will be added to the fable package soon, and will work in combination with fasster.

**Comment by tyokota** [comment]
Thank you for the quick response! I am looking forward to STL.
