### ISSUE TITLE
Levels in state-switching

### ISSUE THREAD

**Issue by tyokota** [mitchelloharawild/fasster#36]
Can state-switching only handle 2 levels? {0,1}

I had tried with three, but the forecast resulted in a flat line (y_hat=0)

**Comment by mitchelloharawild** [comment]
Switching should work for `n` levels, could you provide a minimal reproducible example?

**Comment by tyokota** [comment]
Ah I think the issue is overlapping... If I had hourly data and wanting to instead add a multiple season, could I then do something like this? 
```
fit <- train %>%
  fasster(y ~ business_day %S% (poly(1) + trig(24, 10) + seas(12))) + humidity+ cdd)
```

**Comment by mitchelloharawild** [comment]
That's a valid fable model, yes.
Although I'm not sure what seas(12) is trying to achieve. That would be a seasonal pattern that repeats every 12 hours.

**Comment by tyokota** [comment]
Hm... that's what I had guessed. Is there a way to create some sort of monthly from hourly? I don't see that in Dr. Hyndman's post and I'm guessing it's because months have different days and therefore hours. The other way would be just to create 11 dummy features for the 12 months? Or..

```
fit <- train %>%
  fasster(y ~ month %S% business_day %S% (poly(1) + trig(24, 10) + seas(12))) + humidity+ cdd)
```

https://robjhyndman.com/hyndsight/seasonal-periods/

**Comment by mitchelloharawild** [comment]
I presume that you're trying to model annual seasonality...

If you had monthly data, there are 12 months in a year, so your frequency is 12.

You have hourly data, so there are 8766 hours in a year. Using `seas(8766)` would create 8766 terms in your model (far too many), so you should use `trig` to reduce the number of terms substantially.

**Comment by tyokota** [comment]
Yeah, unfortunately, I only have 1 year of hourly data which is making this task very difficult. If I used the `trig` parameter, then something like `trig(8766, K)`?

```
fit <- train %>%
  fasster(y ~ business_day %S% (poly(1) + trig(24, 10) + trig(8766, K))) + humidity+ cdd)
```

**Comment by mitchelloharawild** [comment]
Yes, that is the idea.

**Comment by tyokota** [comment]
Great! Thank you, again.
