### ISSUE TITLE
Error in .subset2(public_bind_env, "initialize")

### ISSUE THREAD

**Issue by bdemeshev** [mitchelloharawild/fasster#41]
```r
fit <- USAccDeaths %>% 
  as_tsibble %>% 
  model(fasster = FASSTER(value ~ poly(1) + trig(12)))
```
gives an error
`Error in .subset2(public_bind_env, "initialize")(...) : argument ".env" is missing, with no default`

**Comment by mitchelloharawild** [comment]
Sorry about this! Everything should work fine now.
