### ISSUE TITLE
Error when running "forecast"

### ISSUE THREAD

**Issue by jpzhangvincent** [mitchelloharawild/fasster#44]
I just followed the code example on the README but when I tried to run the forecasting function, I got an error message "Error: x is not a tsibble". Any ideas? Thanks in advance!

```r
library(fable)
fit <- as_tsibble(USAccDeaths) %>% 
  model(fasster = FASSTER(value ~ poly(1) + trig(12)))
fit %>% 
  forecast(h=24) %>%
  autoplot(as_tsibble(USAccDeaths))
```

**Comment by mitchelloharawild** [comment]
fasster is set to work with the CRAN version of tsibble. This is because we
are planning to release fable (and possibly fasster) within the next few
weeks. If you install tsibble from CRAN it should work fine.
