### ISSUE TITLE
How can  I get multicore performance using fable and fasster?

### ISSUE THREAD

**Issue by brunocarlin** [mitchelloharawild/fasster#45]
I have a tsibble from this competion https://www.kaggle.com/c/demand-forecasting-kernels-only/overview, fasster is truly fast and cool, but I think I can get 4x performance if I can fit the model on 4 cores.

**Comment by edvardoss** [comment]
> 
> 
> I have a tsibble from this competion https://www.kaggle.com/c/demand-forecasting-kernels-only/overview, fasster is truly fast and cool, but I think I can get 4x performance if I can fit the model on 4 cores.

use nested frames + [furrr](https://cran.r-project.org/web/packages/furrr/index.html)

**Comment by mitchelloharawild** [comment]
Parallel computing using [future](https://github.com/HenrikBengtsson/future) is supported in the `model()` function.

```r
library(fasster)
library(future)

plan(multiprocess)
tsibble::tourism %>% model(fasster::fasster(Trips ~ poly(1) + season(4)))
```
